19-05-2022/MvcProjeKampi/Controllers/AdminLoginController.cs
using BusinessLayer.Conctrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MvcProjeKampi.Controllers
{
    [AllowAnonymous]
    public class AdminLoginController : Controller
    {
        // GET: AdminLogin

        AdminManager am = new AdminManager(new EFAdminDal());

        [HttpGet]

        public ActionResult AdminLoginIndex()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminLoginIndex(Admin admin)
        {

            var AdminInfo = am.GetBySession(admin);


            if (AdminInfo != null)
            {


                FormsAuthentication.SetAuthCookie(AdminInfo.AdminSystemName, false);

                Session["AdminSystemName"] = AdminInfo.AdminSystemName;
                


                return RedirectToAction("AdminListUser", "AdminPanel");


            }
            else
            {
                TempData["AlertMessageStudent"] = "Giriş Yapılamadı ";
                return RedirectToAction("Index");
            }

         
        }


    }
}

19-05-2022/MvcProjeKampi/Views/AdminLogin/AdminLoginIndex.cshtml
@{
    Layout = null;
}




<!DOCTYPE html>

<html lang="tr"
      class="light-style customizer-hide"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="../assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Giriş Yap</title>

    <meta name="description" content="" />
    <link rel="icon" href="~/logo.png">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/pages/page-auth.css" />
    <script src="~/Web2/assets/vendor/js/helpers.js"></script>
    <script src="~/Web2/assets/js/config.js"></script>
</head>

<body>



    <div class="container-xxl">
        <div class="authentication-wrapper authentication-basic container-p-y">
            <div class="authentication-inner">
                <!-- Content -->
                @if (TempData["AlertMessage"] != null)
                {<div class="alert alert-success">
                        <strong> Başarılı ! </strong>@TempData["AlertMessage"]
                    </div>

                }
                <!-- Register -->
                <div class="card">
                    <div class="card-body">
                        <h4 class="mb-2">Hayatım QR Admin Panel 👋</h4>
                        <p class="mb-4">Admin Panel Giriş </p>

                        @using (Html.BeginForm("AdminLoginIndex", "AdminLogin", FormMethod.Post))
                        {
                            <div class="mb-3">
                                <label for="email" class="form-label">Admin Kullanıcı Ad </label>
                                <input type="text"
                                       class="form-control"
                                       id="AdminSystemName"
                                       name="AdminSystemName"
                                       placeholder=" "
                                       autofocus />
                            </div>
                            <div class="mb-3 form-password-toggle">
                                <div class="d-flex justify-content-between">
                                    <label class="form-label" for="password">Admin Kullanıcı Şifre</label>

                                </div>
                                <div class="input-group input-group-merge">
                                    <input type="password"
                                           id="UserPassword"
                                           class="form-control"
                                           name="AdminPassword"
                                           placeholder="***************"
                                           aria-describedby="password" />
                                    <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                                </div>
                            </div>
                            <div class="mb-3">
                                <button class="btn btn-primary d-grid w-100" type="submit">Giriş Yap</button>
                            </div>
                        }
                        <p class="text-center">
                            <span>Ya da</span>
                            <a href="/Homepage1/Index/">
                                <span>Anasayfaya Dön</span>
                            </a>
                        </p>



                        @if (TempData["AlertMessageStudent"] != null)
                        {<div class="alert alert-danger">
                                <strong style="margin-left:750px"> *Hatalı kullanıcı adı ya da şifre ! </strong>@TempData["AlertMessageStudent"]
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <script src="~/Web2/assets/js/main.js"></script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>