19-05-2022/MvcProjeKampi/Controllers/UserHomeController.cs
using BusinessLayer.Conctrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{

    public class UserHomeController : Controller
    {
        // GET: UserHome
        PetQRManager pqrm = new PetQRManager(new EFPetQRDal());
        UserManager um = new UserManager(new EFUserDal());
        ContactManager cm = new ContactManager(new EFContactDal());


        public User SessionValue()
        {
            string p;
            p = (string)Session["UserSystemName"];
            var UserValue = um.GetSessionValue(p);
            return UserValue;
        }

        public ActionResult UserWelcomePage()
        {


            return View();
        }


     
        [Authorize(Roles = "A")]
        public ActionResult HowToUse()
        {
           

            return View(SessionValue());
        }

    



        [HttpGet]
        [Authorize(Roles = "A")]
        public ActionResult QRUpdate()
        {
            ViewBag.userValue = SessionValue();
          var petqrValue =  pqrm.GetByID(SessionValue().UserID);
            return View(petqrValue);
        }


        [HttpPost]
        public ActionResult QRUpdate(PetQR petQR)
        {


            //try
            //{
            Random randm = new Random();

            if (Request.Files.Count > 0)
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                if (filename == "")
                {
                    
                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));
                        petQR.PetImage = "/ımage/" + filename + rdn + uzanti;
                    }
                }


            }

           
            var petqrValue = pqrm.GetByID(SessionValue().UserID);

            petqrValue.PetAge = petQR.PetAge;
            petqrValue.PetImage = petQR.PetImage;
            petqrValue.PetName = petQR.PetName;
            petqrValue.PetOwnerName = petQR.PetOwnerName;
            petqrValue.PetOwnerPhone = petQR.PetOwnerPhone;
            petqrValue.PetOwnerSurName = petQR.PetOwnerSurName;
            petqrValue.PetWarning = petQR.PetWarning;
            petqrValue.PetWarning2 = petQR.PetWarning2;
            petqrValue.SpecialNote = petQR.SpecialNote;
            


            pqrm.PetQRUpdate(petqrValue);

            TempData["AlertMessage1"] = "PetQr Sayfanız Güncellendi.";
            return RedirectToAction("QRUpdate");

    



        }

        [Authorize(Roles = "A")]
        public ActionResult QRView()
        {
    
           var viewpetqr = pqrm.GetByID(SessionValue().UserID);
           ViewBag.UserName = SessionValue().UserName;
           ViewBag.UserSurname = SessionValue().UserSurname;
           ViewBag.UserImage = SessionValue().UserImage;

            return View(viewpetqr);
        }



        [HttpGet]
        public ActionResult Contact()
        {

            

            return View(SessionValue());
        }

        [HttpPost]
        public ActionResult Contact(Contact contact)
        {
          
            contact.UserID = SessionValue().UserID;

            cm.AddValue(contact);

            TempData["AlertMessage1"] = "Destek Talebi Gönderildi.";
            return RedirectToAction("Contact");
        }

        public ActionResult ContactFollow()
        {
          

            ViewBag.uservalue = SessionValue();
            int userid = SessionValue().UserID;


            var requestList = cm.GetByUserID(userid);

            return View(requestList);
        }


        [HttpGet]
        public ActionResult ProfilSetting()
        {
         




            return View(SessionValue());
        }

        [HttpPost]
        public ActionResult ProfilSetting(User user)
        {
            string p;
            p = (string)Session["UserSystemName"];
            var userValue = um.GetSessionValue(p);



            Random randm = new Random();

            if (Request.Files.Count > 0)
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                if (filename == "")
                {

                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));
                        user.UserImage = "/ımage/" + filename + rdn + uzanti;
                    }
                }


            }



            if (user.UserPasswordOld == userValue.UserPassword)
            {

                user.UserPasswordOld = null;
                userValue.UserPassword = user.UserPassword;
                userValue.UserImage = user.UserImage;
                TempData["AlertMessage1"] = "Güncelleme Yapıldı ";
                um.Update(userValue);
                return RedirectToAction("ProfilSetting");
            }
            else
            {
                TempData["AlertMessage2"] = "Güncelleme Yapılamadı ";
                return RedirectToAction("ProfilSetting");
            }


        }

    }
}

19-05-2022/MvcProjeKampi/Views/UserHome/Contact.cshtml
@model EntityLayer.Concrete.User
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}










<!DOCTYPE html>
<html>
<head>
    <link href="~/Extra/forcontact.css" rel="stylesheet" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | User Profile</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Extra/forcontact.css" rel="stylesheet" />
    <!-- Font Awesome -->
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/72d82a5a39.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Extra/userviewcs.css" rel="stylesheet" />
    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <style>
        .avatar {
            vertical-align: middle;
            width: 50px;
            height: 50px;
            border-radius: 50%;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
            height: 50%;
        }
    </style>

</head>


<body>


    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <strong>@Model.UserName @Model.UserSurname</strong>
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <!-- Place this tag where you want the button to render. -->
                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">


                                @if (Model.UserImage == null)
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="~/Extra/images/fre2.png" alt="Avatar" class="avatar" />


                                        </div>
                                    </a>

                                }
                                else
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="@Model.UserImage" alt="Avatar" class="avatar" />

                                        </div>
                                    </a>
                                }




                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">

                        <div class="row">
                            <div class="col-md-12">

                                <div class="card mb-4">

                                    <!-- Account -->
                                    <main id="main">

                                        <!-- ======= About Section ======= -->
                                        <!-- ======= Clients Section ======= -->
                                        <!-- ======= Features Section ======= -->




                                        <div class="contact-clean">


                                            @using (Html.BeginForm("Contact", "UserHome", FormMethod.Post))
                                            {

                                                <h2 class="text-center" style="font-weight:bold">Destek Talebi</h2>


                                                <div class="form-group"><input class="form-control" type="text" name="Subjet" placeholder="Konu"></div>
                                                <div class="form-group"><input class="form-control" type="hidden" name="UserID" placeholder="Konu" value="@ViewBag.userid"></div>

                                                <br />
                                                <div class="form-group"><textarea class="form-control" name="Content" placeholder="Mesaj İçeriği" rows="14"></textarea></div>

                                                <br />
                                                <button class="btn btn-primary d-grid w-100" type="submit">Gönder</button>

                                            }

                                            <br />

                                        </div>






                                    </main>
                                    <!--




                                    <!-- /Account -->
                                </div>
                                @if (TempData["AlertMessage1"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color:white"> Başarılı ! @TempData["AlertMessage1"] </strong>
                                    </div>

                                }
                                @if (TempData["AlertMessage2"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color:white"> Başarısız ! @TempData["AlertMessage2"] </strong>
                                    </div>

                                }
                            </div>

                        </div>
                    </div>


                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->

    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/Web2/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/Web2/assets/js/pages-account-settings-account.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>


</body>


</html>

19-05-2022/MvcProjeKampi/Views/UserHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Index</h2>

19-05-2022/MvcProjeKampi/Views/UserHome/ProfilSetting.cshtml
@model EntityLayer.Concrete.User


@{
    ViewBag.Title = "ProfilSetting";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}











<!DOCTYPE html>
<html>
<head>
    <link href="~/Extra/forcontact.css" rel="stylesheet" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | User Profile</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Extra/forcontact.css" rel="stylesheet" />
    <!-- Font Awesome -->
   
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
  
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap-extended.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/fonts/simple-line-icons/style.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/colors.min.css">
    <link rel="stylesheet" type="text/css" href="https://pixinvent.com/stack-responsive-bootstrap-4-admin-template/app-assets/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/72d82a5a39.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <link href="~/Extra/userviewcs.css" rel="stylesheet" />
    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <style>
        .avatar {
            vertical-align: middle;
            width: 50px;
            height: 50px;
            border-radius: 50%;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 50%;
            height: 50%;
        }
    </style>

</head>


<body>


    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <strong>@Model.UserName @Model.UserSurname</strong>
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <!-- Place this tag where you want the button to render. -->
                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">


                                @if (Model.UserImage == null)
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="~/Extra/images/fre2.png" alt="Avatar" class="avatar" />


                                        </div>
                                    </a>

                                }
                                else
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="@Model.UserImage" alt="Avatar" class="avatar" />

                                        </div>
                                    </a>
                                }




                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">

                        <div class="row">
                            <div class="col-md-12">

                                <div class="card mb-4">

                                    <!-- Account -->
                                    <main id="main">

                                        <!-- ======= About Section ======= -->
                                        <!-- ======= Clients Section ======= -->
                                        <!-- ======= Features Section ======= -->




                                        <div class="contact-clean">

                                            @using (Html.BeginForm("ProfilSetting", "UserHome", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                            {
                                                <div class="form-group">






                                                    <br />
                                                    <div style="margin-left:20px">
                                                        @Html.Label("Eski Şifre")
                                                        <div class="form-group"><input class="form-control" type="text" name="UserPasswordOld" placeholder="*************"></div>

                                                    </div>

                                                    <br />
                                                    <div style="margin-left:20px">
                                                        @Html.Label("Yeni Şifre")
                                                        @*@Html.TextBoxFor(x => x.activityPrice, new { @class = "form-control" })*@
                                                        <div class="form-group"><input class="form-control" type="text" name="UserPassword" placeholder="*************"></div>

                                                    </div>

                                                    <br />
                                                    <div style="margin-left:20px">
                                                        <div class="mb-3">

                                                            @Html.Label("Profil Fotoğrafı")
                                                            <input type="file"
                                                                   class="form-control"
                                                                   id="UserImage"
                                                                   name="UserImage"
                                                                   placeholder="Profil Fotoğrafı Yükleyin"
                                                                   autofocus />
                                                        </div>
                                                    </div>







                                                </div>
                                                <br />
                                                <br />
                                                <div style="margin-left:20px">
                                                    <button class="btn btn-info text-center  form-control " style="color:white"> Güncelle </button>
                                                </div>

                                            }


                                            <br />

                                        </div>






                                    </main>
                                    <!--




                                    <!-- /Account -->
                                </div>
                                @if (TempData["AlertMessage1"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color:white"> Başarılı ! @TempData["AlertMessage1"] </strong>
                                    </div>

                                }
                                @if (TempData["AlertMessage2"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color:white"> Başarısız ! @TempData["AlertMessage2"] </strong>
                                    </div>

                                }
                            </div>

                        </div>
                    </div>


                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->

    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/Web2/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/Web2/assets/js/pages-account-settings-account.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>


</body>


</html>

19-05-2022/MvcProjeKampi/Views/UserHome/QRViewPublic.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QRViewPublic</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

19-05-2022/MvcProjeKampi/Views/UserHome/UserWelcomePage.cshtml
@{
    ViewBag.Title = "UserWelcomePage";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>404 HTML Tempalte by Colorlib</title>

    <!-- Google font -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

    <!-- Custom stlylesheet -->
    <link type="text/css" rel="stylesheet" href="~/Extra/404NotFound/css/style.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body>

    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <h1>Giriş Başarılı!</h1>

            </div>
          


            @if (User.IsInRole("A"))
            {
                <a href="/UserHome/HowToUse">Nasıl Kullanılır Öğrenelim</a>
            }
            @if (User.IsInRole("B"))
            {

                <a href="/UserHomeB/HowToUseMenu">Nasıl Kullanılır Öğrenelim</a>
            }

        </div>
    </div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>


<div class="text-center">

</div>