19-05-2022/MvcProjeKampi/Controllers/UserHomeBController.cs
using BusinessLayer.Conctrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class UserHomeBController : Controller
    {

        UserManager um = new UserManager(new EFUserDal());
        ContactManager cm = new ContactManager(new EFContactDal());
        MenuQrManager mqm = new MenuQrManager(new EFMenuQrDal());
        MenuQrCategoryManager mqcm = new MenuQrCategoryManager(new EFMenuQrCategoryDal());
        MenuQrHeadingManager mqhm = new MenuQrHeadingManager(new EFMenuQrHeadingDal());
        // GET: UserHomeB



        public User SessionValue()
        {
            string p;
            p = (string)Session["UserSystemName"];
            var UserValue = um.GetSessionValue(p);
            return UserValue;
        }

        [Authorize(Roles = "B")]
        public ActionResult HowToUseMenu()
        {
           

            return View(SessionValue());
        }

        [Authorize(Roles = "B")]
        [HttpGet]
        public ActionResult MenuQrCategoryAdd()
        {
            
            return View(SessionValue());
        }
        [HttpPost]
        public ActionResult MenuQrCategoryAdd(MenuQrCategory MenuQrCategory)
        {
  
            MenuQrCategory.UserID = SessionValue().UserID;


            Random randm = new Random();

            if (Request.Files.Count > 0)
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                if (filename == "")
                {
                    MenuQrCategory.CategoryImage = "/Extra/images/fooddef.png";
                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));


                        MenuQrCategory.CategoryImage = "/ımage/" + filename + rdn + uzanti;
                       
                        
                    }
                }


            }

            
                mqcm.AddValue(MenuQrCategory);


            TempData["AlertMessage1"] = "Menü Qr Kategoriniz Eklendi.";
            return RedirectToAction("MenuQrCategoryAdd");
        }



        public ActionResult SeeMenuQrCategories()
        {
            ViewBag.uservalue = SessionValue();

            var ListCategories = mqcm.GetByUserID(SessionValue().UserID);

            return View(ListCategories);
        }


        public ActionResult SeeMenuQrList()
        {
            ViewBag.uservalue = SessionValue();

            var ListCategories = mqcm.GetByUserID(SessionValue().UserID);

            return View(ListCategories);
        }

        public ActionResult SeeMenuContentList(int id)
        {
            ViewBag.uservalue = SessionValue();

            var ListCategories = mqhm.GetByIDListWithCat(id);

            return View(ListCategories);
        }

        public ActionResult EditMenuContent(int id)
        {
            ViewBag.uservalue = SessionValue();

            var ListCategories = mqhm.GetByIDListWithCat(id);

            return View(ListCategories);
        }

        [HttpGet]
        public ActionResult EditMenuContentPage(int id)
        {
            

            var contentValue = mqhm.GetByID(id);

            return View(contentValue);
        }

        [HttpPost]
        public ActionResult EditMenuContentPage(MenuQrHeading menuQrHeading)
        {

            Random randm = new Random();

            if (Request.Files.Count > 0)
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                var getvalue = mqhm.GetByID(menuQrHeading.MenuQrHeadingID);

                if (filename == "")
                {
                    string valueımage = getvalue.HeadingImage;

                    menuQrHeading.HeadingImage = valueımage;
                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));


                        menuQrHeading.HeadingImage = "/ımage/" + filename + rdn + uzanti;


                    }
                }


            }



            mqhm.MenuQrHeadingUpdate(menuQrHeading);
            int id = menuQrHeading.MenuQrCategoryID;
            TempData["AlertMessageUpdate"] = "Seçilen İçerik Güncellendi.";
            return RedirectToAction("EditMenuContent", new { id = id });
        }


        public ActionResult DeleteMenuContent(int id)
        {
            var value = mqhm.GetByID(id);
            int Headingid = value.MenuQrCategoryID;
            mqhm.MenuQrHeadingDelete(value);


            TempData["AlertMessageDelete"] = "Seçilen İçerik Silindi.";
            return RedirectToAction("EditMenuContent", new { id = Headingid });
        }


        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
           

            var catupdatevalue = mqcm.GetByID(id);


            return View(catupdatevalue);
        }
        [HttpPost]
        public ActionResult UpdateCategory(MenuQrCategory value)
        {
           

            Random randm = new Random();

            var valueforupdate = mqcm.GetByID(value.MenuQrCategoryID);

            if (Request.Files.Count > 0 || Request.PathInfo != "")
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;
               
                if (filename == "")
                {
                      
                   
                    string valueımage = valueforupdate.CategoryImage;

                    value.CategoryImage = valueımage;

                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));


                        value.CategoryImage = "/ımage/" + filename + rdn + uzanti;


                    }
                }


            }




            var valueid = valueforupdate.MenuQrCategoryID;


            mqcm.MenuQrCategoryNewUpdate(value, valueid);

            //mqcm.AddValue(value);

            TempData["AlertMessage3"] = "Seçilen Kategori Güncellendi.";
            return RedirectToAction("SeeMenuQrCategories");
        }


        public ActionResult DeleteCategory(int id)
        {
    

           var catdeletevalue =  mqcm.GetByID(id);
            mqcm.MenuQrCategoryDelete(catdeletevalue);
            TempData["AlertMessage1"] = "Seçilen Kategori Silindi.";
            return RedirectToAction("SeeMenuQrCategories");
        }


        [HttpGet]
        public ActionResult AddContent(int id)
        {
            var headingvalue = mqcm.GetByID(id);

          
                return View(headingvalue);
          
        
           
          
        }

        [HttpPost]
        public ActionResult AddContent(MenuQrHeading menuQrHeading)
        {

            try
            {

                Random randm = new Random();

            

                if (Request.Files.Count > 0 || Request.PathInfo != "")
                {
                    string rdn = Convert.ToString(randm.Next(0, 9999));
                    string filename = Path.GetFileName(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);
                    string yol = "~/ımage/" + filename + rdn + uzanti;

                    var getvalue = mqcm.GetByID(menuQrHeading.MenuQrCategoryID);
                    if (filename == "")
                    {


                        string valueımage = getvalue.CategoryImage;

                        menuQrHeading.HeadingImage = valueımage;

                    }
                    else
                    {
                        if (yol == "~/ımage/")
                        {

                        }
                        else
                        {

                            Request.Files[0].SaveAs(Server.MapPath(yol));


                            menuQrHeading.HeadingImage = "/ımage/" + filename + rdn + uzanti;


                        }
                    }


                }





                mqhm.AddValue(menuQrHeading);


                TempData["AlertMessageContent1"] = "Yeni İçerik Eklendi.";
            }
            catch
            {
                TempData["AlertMessageContent2"] = "Ekleme tamamlanmadı.";
            }
        
            return RedirectToAction("AddContent",menuQrHeading.MenuQrCategoryID);
        }






    }
}

19-05-2022/MvcProjeKampi/Views/UserHomeB/EditMenuContent.cshtml
@using EntityLayer.Concrete
@model List<MenuQrHeading>

@{
    ViewBag.Title = "EditMenuContent";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}





@{ string color = "";}
@{ int dgr = 0;}



<!DOCTYPE html>
<html lang="en">



<body>





    <!-- / Navbar -->
    <!-- Content wrapper -->
    <!-- Content wrapper -->
    <!-- ======= Footer ======= -->


    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>



    <!-- Template Main JS File -->
    <script src="~/Extra/Homepage/Login/assets/js/main.js"></script>

</body>

</html>


<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/Web2/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Account settings - Account | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/Web2/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="../assets/js/config.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <strong>@ViewBag.uservalue.UserName @ViewBag.uservalue.UserSurname</strong>
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <!-- Place this tag where you want the button to render. -->
                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">


                                @if (ViewBag.uservalue.UserImage == null)
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="~/Extra/images/fre2.png" alt="Avatar" class="avatar" />


                                        </div>
                                    </a>

                                }
                                else
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="@ViewBag.uservalue.UserImage" alt="Avatar" class="avatar" />

                                        </div>
                                    </a>
                                }




                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">

                        @if (TempData["AlertMessageDelete"] != null)
                        {<div class="alert alert-info ">
                                <strong class="text-center" style="color: blueviolet"> Başarılı ! @TempData["AlertMessageDelete"] </strong>
                            </div>

                        }
                        @if (TempData["AlertMessageUpdate"] != null)
                        {<div class="alert alert-info ">
                                <strong class="text-center" style="color: blueviolet"> Başarılı ! @TempData["AlertMessageUpdate"] </strong>
                            </div>

                        }


                        <div class="row">

                            @foreach (var item in Model)
                            {

                                if (dgr == 0)
                                {
                                    color = "border-primary";

                                }
                                if (dgr == 1)
                                {
                                    color = "border-secondary";

                                }
                                if (dgr == 2)
                                {
                                    color = "border-success";

                                }
                                if (dgr == 3)
                                {
                                    color = "border-danger";

                                }
                                if (dgr == 4)
                                {
                                    color = "border-warning";

                                }
                                if (dgr == 5)
                                {
                                    color = "border-info";
                                    dgr = 0;
                                }






                                <div class="col-md-6 col-xl-4">
                                    <div class="card shadow-none bg-transparent border @color mb-3">


                                        <div class="card-body">


                                            <p class="card-title" style="text-align:center"><img class="card-img-top" src="@item.HeadingImage" alt="Card image cap" style="width:100px;height:100px" /></p>

                                            <h3 class="card-title" style="text-align:center;font-weight:bold"> @item.HeadingName </h3>
                                            <p class="card-text" style="text-align:center">@item.FirstContent </p>
                                            <p class="card-text" style="text-align:center">@item.SecondaryContent</p>
                                            <p class="card-text" style="text-align:center">@item.productPrice TL</p>


                                            <p class="card-text" style="text-align:center"><a href="/UserHomeB/EditMenuContentPage/@item.MenuQrHeadingID" class="btn btn-outline-primary">İçerik Güncelle</a> <a  style="margin-left:5px "href="/UserHomeB/DeleteMenuContent/@item.MenuQrHeadingID" class="btn btn-outline-danger">İçerik Sil</a> </p>

                                            @if (true)
                                            {
                                                dgr++;
                                            }
                                        </div>
                                    </div>
                                </div>
                            }


                        </div>




                    </div>



                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->

    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/Web2/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/Web2/assets/js/pages-account-settings-account.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>

19-05-2022/MvcProjeKampi/Views/UserHomeB/MenuQrCategoryAdd.cshtml
@model EntityLayer.Concrete.User

@{
    ViewBag.Title = "MenuQrCategoryAdd";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}



<!DOCTYPE html>

<style>
    .avatar {
        vertical-align: middle;
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }
</style>
<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->


<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/Web2/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Account settings - Account | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/Web2/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="../assets/js/config.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <strong>@Model.UserName @Model.UserSurname</strong>
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <!-- Place this tag where you want the button to render. -->
                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">


                                @if (Model.UserImage == null)
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="~/Extra/images/fre2.png" alt="Avatar" class="avatar" />


                                        </div>
                                    </a>

                                }
                                else
                                {
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="@Model.UserImage" alt="Avatar" class="avatar" />

                                        </div>
                                    </a>
                                }




                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">

                        <div class="row">
                            <div class="col-md-12">

                                <div class="card mb-4">

                                    <!-- Account -->

                                    @using (Html.BeginForm("MenuQrCategoryAdd", "UserHomeB", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        <div class="card-body">
                                            <div class="d-flex align-items-start align-items-sm-center gap-4">
                                                <img src="~/Extra/images/deffood.jpg"
                                                     alt="user-avatar"
                                                     class="d-block rounded"
                                                     height="180"
                                                     width="180"
                                                     id="uploadedAvatar" />
                                                <div class="button-wrapper">
                                                    <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                                                        <span class="d-none d-sm-block">Fotoğraf Yükle</span>
                                                        <i class="bx bx-upload d-block d-sm-none"></i>
                                                        <input type="file"
                                                               id="upload"
                                                               name="CategoryImage"
                                                               class="account-file-input"
                                                               hidden
                                                               accept="image/png, image/jpeg" />
                                                    </label>


                                                    <p class="text-muted mb-0">Yanlızca Jpg ve Png formatında yükleme yapınız. </p>
                                                </div>
                                            </div>
                                        </div>
                                        <hr class="my-0" />
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="mb-3 col-md-6">
                                                    <label for="firstName" class="form-label">Kategori İsmi</label>
                                                    <input class="form-control"
                                                           type="text"
                                                           id="firstName"
                                                           name="CategoryName"
                                                           value=""
                                                           placeholder="Makarnalar vs.."
                                                           autofocus />
                                                </div>

                                               


                                                <div class="mb-3 col-md-6">


                                                </div>
                                                <div class="mb-3 col-md-6">

                                                </div>


                                            </div>





                                            <div class="mt-2">
                                                <button type="submit" class="btn btn-primary me-2">Kategori Ekle</button>
                                                <button type="reset" class="btn btn-outline-secondary">Vazgeç</button>
                                            </div>



                                        </div>
                                    }
                                    <!-- /Account -->
                                </div>
                                @if (TempData["AlertMessage1"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color: blueviolet"> Başarılı ! @TempData["AlertMessage1"] </strong>
                                    </div>

                                }
                                @if (TempData["AlertMessage2"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color:blueviolet"> Başarısız ! @TempData["AlertMessage2"] </strong>
                                    </div>

                                }
                            </div>

                        </div>
                    </div>


                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->

    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/Web2/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/Web2/assets/js/pages-account-settings-account.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>